server:
  port: 8888
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
<<<<<<< HEAD
          search-paths: 'desenvolvimento, homologacao, producao, usuario'
          uri: 'https://github.com/HarturAlcantaraDev/config-server'
server:
  port: '8888'

=======
          search-paths: desenvolvimento, homologacao, producao, usuario
          uri: https://github.com/HarturAlcantaraDev/config-server
>>>>>>> refs/heads/release-homologacao
