spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          search-paths: 'desenvolvimento, homologacao, producao, usuario'
          uri: 'https://github.com/HarturAlcantaraDev/config-server'
server:
  port: '8888'

